function [currentContrast,n,m,butt,f2,...
    PNGrslts_MetaData,pngCounter,f1,resltMTX,whoMTX,reviewCntr] =  keytry2(varargin);

% clb 2013
%v4.0 04/04/13 - keyboard shortcuts for lighten/darken/done

% each time a key is pressed, keytry2 repopulated with varagin inputs, so
% varagin is what should be inputs here, not resltMTX....

% varagin gets populated by the variable listed at the bottom of the
% SoundChecker mfile (i.e.,  set(f2,'WindowKeyPressFcn',{@keytry2....)
% so butt is 3, pngfolder is 4, wavefolder is 5, fileMTX is 6,....

% Getvars are a little different:  1 is butt, 2 is pngFolder, 3 is WaveFolder, 4 is fileMTX,
% 5 is n, 6 is m, 7 is currentContrast... so basically it is same as
% varargin, but numbered 2 less for each.

Getvars = get(varargin{20},'WindowKeyPressFcn');
butt = Getvars{2};
currentContrast = Getvars{8};
pngCounter = Getvars{10};
n = Getvars{6};
m = Getvars{7};

butt = varargin{3};
if get(butt.review,'Value') ~= 1 & get(butt.hop_to,'Value') ~=1;
    switch  varargin{2}.Key
        case 'leftarrow'
            set(varargin{3}.light,'Value',1);
            
            [PNGrslts_MetaData,currentContrast,n,m,pngCounter] = ...
                lighten(varargin{3},varargin{4},  varargin{5},varargin{6},n, ...
                m,varargin{9},varargin{12},varargin{20},varargin{10}, ...
                varargin{11},varargin{13},varargin{14},varargin{15},varargin{16},...
                varargin{17},varargin{18},varargin{19});
            set(varargin{3}.light,'Value',0);
            
            set(varargin{3}.light,'Enable','off');
            drawnow;
            set(varargin{3}.light,'Enable','on');
            f2 = varargin{20};
            f1 = varargin{12};
            
            set(f2,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13}, varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},varargin{22},varargin{23}});
            set(f1,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13},varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},varargin{22},varargin{23}});
            
        case 'rightarrow'
            set(varargin{3}.dark,'Value',1);
            [PNGrslts_MetaData,currentContrast,n,m,pngCounter] = ...
                darken(varargin{3},varargin{4},  varargin{5},varargin{6},n, ...
                m,varargin{9},varargin{12},varargin{20},varargin{10}, ...
                varargin{11},varargin{13},varargin{14},varargin{15},varargin{16},...
                varargin{17},varargin{18},varargin{19});
            set(varargin{3}.dark,'Value',0);
            
            set(varargin{3}.dark,'Enable','off');
            drawnow;
            set(varargin{3}.dark,'Enable','on');
            f2 = varargin{20};
            f1 = varargin{12};
            
            set(f2,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13}, varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},varargin{22},varargin{23}});
            set(f1,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13},varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},varargin{22},varargin{23}});
            
        case 'space'
                       [resltMTX,whoMTX,butt,n,m,currentContrast,PNGrslts_MetaData,pngCounter,f1,f2] = ...
                button(varargin{13}, varargin{6}, varargin{14}, ...
                varargin{15},varargin{5}, varargin{16},varargin{4},varargin{3},n,m,varargin{17}, ...
                varargin{10}, varargin{9},varargin{18},varargin{19}, varargin{11},varargin{12},varargin{20});
            set(f2,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,pngCounter, ...
                varargin{12},resltMTX,  whoMTX,varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},varargin{22},varargin{23}});
            set(f1,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,pngCounter, ...
                varargin{12}, varargin{13},varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},varargin{22},varargin{23}});
             
           
            set(varargin{3}.obj2,'Enable','off');  % the Done button
            drawnow;
            
            set(varargin{3}.obj2,'Enable','on');  % the Done button
            
    end
    
elseif get(butt.review,'Value') == 1 |  get(butt.hop_to,'Value') == 1;
    switch  varargin{2}.Key
        case 'leftarrow'
            set(varargin{3}.light,'Value',1);
            
            [PNGrslts_MetaData,currentContrast,n,m,pngCounter] = ...
                lighten(varargin{3},varargin{4},  varargin{5},varargin{6},varargin{7}, ...
                varargin{8},varargin{9},varargin{12},varargin{20},varargin{10}, ...
                varargin{11},varargin{13},varargin{14},varargin{15},varargin{16},...
                varargin{17},varargin{18},varargin{19});
            
            set(varargin{3}.light,'Value',0);
            
            set(varargin{3}.light,'Enable','off');
            drawnow;
            set(varargin{3}.light,'Enable','on');
            f2 = varargin{20};
            f1 = varargin{12};
            
            set(f2,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13}, varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},varargin{22},varargin{23}});
            set(f1,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13},varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},varargin{22},varargin{23}});
            Getvars = get(f2,'WindowKeyPressFcn');
            resltMTX = Getvars{12};
            whoMTX = Getvars{13};
            butt = Getvars{2};
            reviewCntr = Getvars{21};
            currentContrast = Getvars{8};
            
        case 'rightarrow'
            set(varargin{3}.dark,'Value',1);
            [PNGrslts_MetaData,currentContrast,n,m,pngCounter] = ...
                darken(varargin{3},varargin{4},  varargin{5},varargin{6},varargin{7}, ...
                varargin{8},varargin{9},varargin{12},varargin{20},varargin{10}, ...
                varargin{11},varargin{13},varargin{14},varargin{15},varargin{16},...
                varargin{17},varargin{18},varargin{19});
            set(varargin{3}.dark,'Value',0);
            
            set(varargin{3}.dark,'Enable','off');
            drawnow;
            set(varargin{3}.dark,'Enable','on');
            f2 = varargin{20};
            f1 = varargin{12};
            
            set(f2,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13}, varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},varargin{22},varargin{23}});
            set(f1,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13},varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},varargin{22},varargin{23}});
            
            Getvars = get(f2,'WindowKeyPressFcn');
            resltMTX = Getvars{12};
            whoMTX = Getvars{13};
            butt = Getvars{2};
            reviewCntr = Getvars{21};
            currentContrast = Getvars{8};
            
        case 'f'  % this will be the forwards one
            set(varargin{3}.obj6,'Value',1);
            
            [butt,resltMTX,currentContrast, PNGrslts_MetaData,reviewCntr,n,m,f1,f2,whoMTX] = reviewSCROLL(varargin{6}, ...
                varargin{4}, varargin{13},varargin{18},varargin{10}, ...
                varargin{15},varargin{3},1,varargin{9},varargin{21},varargin{22},varargin{23},varargin{12},varargin{20},varargin{14},varargin{16});
            
            set(butt.obj6,'Value',0);
            set(butt.obj6,'Enable','off');
            drawnow;
            set(butt.obj6,'Enable','on');
            
            set(f2,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13}, varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},reviewCntr,varargin{23}});
            set(f1,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13},varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},reviewCntr,varargin{23}});
            
            Getvars = get(f2,'WindowKeyPressFcn');
            resltMTX = Getvars{12};
            whoMTX = Getvars{13};
            butt = Getvars{2};
            reviewCntr = Getvars{21};
            currentContrast = Getvars{8};
          
        case 'a'  % this will be the backwards one
            set(varargin{3}.obj5,'Value',1);
            [butt,resltMTX,currentContrast, PNGrslts_MetaData,reviewCntr,n,m,f1,f2,whoMTX] = reviewSCROLL(varargin{6}, ...
                varargin{4}, varargin{13},varargin{18},varargin{10}, ...
                varargin{15},varargin{3},-1,varargin{9},varargin{21},varargin{22},varargin{23},varargin{12},varargin{20},varargin{14},varargin{16});
            set(butt.obj5,'Value',0);
            set(butt.obj5,'Enable','off');
            drawnow;
            set(butt.obj5,'Enable','on');
            
            
            set(f2,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12},varargin{13}, varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},reviewCntr,varargin{23}});
            set(f1,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12}, varargin{13},varargin{14},varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},reviewCntr,varargin{23}});
            
            Getvars = get(f2,'WindowKeyPressFcn');
            resltMTX = Getvars{12};
            whoMTX = Getvars{13};
            butt = Getvars{2};
            reviewCntr = Getvars{21};
            
            currentContrast = Getvars{8};
        case  't'  % this one is the shortcut for the change key.
            set(varargin{3}.change,'Value',1);
            [resltMTX,whoMTX,butt,currentContrast,PNGrslts_MetaData,reviewCntr,n,m,f1,f2] = ...
                reviewChange(varargin{13}, varargin{6}, varargin{14}, varargin{15}, ...
                varargin{16}, varargin{4}, varargin{3}, varargin{17}, varargin{21}, ...
                varargin{10}, varargin{9}, varargin{18}, varargin{19},varargin{22},varargin{23},varargin{12},varargin{20});
            set(butt.change,'Value',0);
            set(butt.change,'Enable','off');
            drawnow;
            set(butt.change,'Enable','on');
            
            set(f2,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12},resltMTX, whoMTX,varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},reviewCntr,varargin{23}});
            set(f1,'WindowKeyPressFcn',{@keytry2,butt,varargin{4},varargin{5}, ...
                varargin{6},n,m,currentContrast,PNGrslts_MetaData,varargin{11}, ...
                varargin{12},resltMTX, whoMTX,varargin{15}, varargin{16}, ...
                varargin{17}, varargin{18}, varargin{19},varargin{20},varargin{21},reviewCntr,varargin{23}});
            Getvars = get(f2,'WindowKeyPressFcn');
            resltMTX = Getvars{12};
            whoMTX = Getvars{13};
            butt = Getvars{2};
            reviewCntr = Getvars{21};
            currentContrast = Getvars{8};
    end
    
    
end
